name: Trigger auto deployment for order-api-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/order-api-demo-AutoDeployTrigger-aa6110d7-f160-4ccd-852d-097e2ca07e91.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ORDERAPIDEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ORDERAPIDEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ORDERAPIDEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/sample-app
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrjffjqgwlbwhgc.azurecr.io
          registryUsername: ${{ secrets.ORDERAPIDEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ORDERAPIDEMO_REGISTRY_PASSWORD }}
          containerAppName: order-api-demo
          resourceGroup: rg-srea-demo
          imageToBuild: acrjffjqgwlbwhgc.azurecr.io/order-api-demo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


